spring:
  application:
    name: web-sell-spring-mvc
  profiles:
    default: ${SPRING_PROFILES_ACTIVE:dev}
  datasource:
    username: root
    url: jdbc:mysql://localhost:3306/ltw
    driver-class-name: com.mysql.cj.jdbc.Driver

  main:
    allow-bean-definition-overriding: true

server:
  error:
    whitelabel:
      enabled: false
    path: /error