spring:
  application:
    name: web-sell-spring-mvc
  profiles:
    default: ${SPRING_PROFILES_ACTIVE:dev}
  datasource:
    url: jdbc:mysql://localhost:3306/ltw
    username: root
    driver-class-name: com.mysql.cj.jdbc.Driver
    password: 123
  jpa:
    hibernate:
      ddl-auto: update
  session:
    store-type: jdbc
    jdbc:
      initialize-schema: always
    timeout: 3600

server:
  error:
    whitelabel:
      enabled: false
    path: /error
  port: 8443
  ssl:
    enabled: true
    key-store: classpath:key/keystore.p12
    key-store-password: 123
    key-alias: local-https
    key-store-type: PKCS12

app:
  service:
    cloudinary:
      cloud-name: yourstyle
      api-key: 959271713937367
      api-secret: 3tqA0quB3nZGk6o8qdtOVXN6dP0
    delivery:
      url: https://online-gateway.ghn.vn/shiip/public-api
      province-id: 202
      district-id: 1442
      ward-code: 20101
      weight: 500
      service-type-id: 2
      shop-id: 4969655
      token: 015940b9-e810-11ee-b290-0e922fc774da
    map4d:
      url: https://api.map4d.vn/sdk/v2/geocode
      api-key: 508a31b5c17f02ca9530bf6f8110010e
    google:
      client-id: 336186921669-k0vb5vt05phajcah47psl3v0t4h3eah0.apps.googleusercontent.com
      redirect-uri: http://localhost:${server.port}/oauth2/google/login/callback
      token-uri: https://accounts.google.com/o/oauth2/token
      user-info-uri: https://www.googleapis.com/oauth2/v3/userinfo
      grant-type: authorization_code
      client-secret: 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
      login-uri: https://accounts.google.com/o/oauth2/auth?redirect_uri=${app.service.google.redirect-uri}&scope=email%20profile&client_id=${app.service.google.client-id}&response_type=code
    facebook:
      client-id: 2825100177629702
      client-secret: f52c1f23c0884cccf05178bbbe24f810
      token-uri: https://graph.facebook.com/v19.0/oauth/access_token
      user-info-uri: https://graph.facebook.com/me?fields=id,name,email&access_token=
      redirect-uri: http://localhost:${server.port}/oauth2/facebook/login/callback
      login-uri: https://www.facebook.com/v9.0/dialog/oauth?redirect_uri=${app.service.facebook.redirect-uri}&scope=email&client_id=${app.service.facebook.client-id}
logging:
  level:
    feign:
      Client=DEBUG: DEBUG
